- package-lock.json
- package.json
- src/components/Extra.vue
- src/components/MessageBox/messageBox.vue
- src/components/Panels/PropertiesPanel/ModuleProperty/ModuleProperty.vue
- src/components/Panels/PropertiesPanel/ModuleProperty/ProjectProperty/ProjectProperty.vue
- src/components/TabsBar/TabsBar.vue
- src/main.ts
- src/simulator/src/circuit.js
- src/simulator/src/setup.js
- src/store/SimulatorStore/actions.ts
- src/store/SimulatorStore/state.ts
> feat: tabsbar component

- package.json
- src/components/DialogBox/Themes/ApplyThemes.vue
- vite.config.ts
Fixes #50 
`svgLoader` package which enable us to use SVGs as component.
> was used in the themes dialog box to show theme cards
was blocking the SVG loads of circuit elements in the production.
solve: removed the package.
and in the `themes-dialog box` the `theme cards` are displayed as images.
> fix: remove svgloader and fixed the themes dialog box not showing

- src/components/Navbar/Navbar.css
- src/simulator/src/ux.js
- src/styles/css/main.stylesheet.css
- > **The panels and dropdowns no longer overlaps with each other**.
Fixes: #43
- Changed the z-index of multiple elements to prevent overlapping.
https://user-images.githubusercontent.com/66828942/210682010-aeb6027c-237f-4c96-9dd9-52d2c9254143.mp4
> fix: panel and dropdown overlap

- src/styles/css/main.stylesheet.css
Fixes #80 
I just add "text-decoration:none" under ".navbar-menu > li > a:hover" in "src/styles/css/main.stylesheet.css" file.
> fix: disabled underline on hovering items in Nav Menu

- src/components/DialogBox/Themes/ApplyThemes.vue
- src/styles/css/main.stylesheet.css
Fixes #82
Changed styling of custom theme dialog box and made it responsive.
> style: custom theme dialog box styling

- src/components/ContextMenu/ContextMenu.vue
Fixes #152 
Fixed the double undo bug in the context menu. Now only the undo operation is performed only once instead of twice when we click the undo in the Context Menu.
https://user-images.githubusercontent.com/86093112/228747808-a793d146-cf3f-487b-ae14-424cc4afd916.mp4
> fix: double undo in context menu #152

- netlify.toml
- postcss.config.js
- src/pages/index.vue
- src/router/index.ts
- vite.config.ts
Fixes #165 
set the build directory to  public/simulatorvue folder in the main repository 
```
base: '/simulatorvue/',
build: {
outDir: '../public/simulatorvue',
assetsDir: 'assets',
chunkSizeWarningLimit: 1600,
},
```
change the vue-simulator route from `/simulator` to `/simulatorvue` (for time being until feature flags are added) 
N/A
> feat(gsoc): update vite build directory for vue simualtor integration

- src/assets/constants/Panels/TimingDiagramPanel/buttons.json
- src/components/Extra.vue
- src/components/Panels/Shared/PanelHeader.vue
- src/components/Panels/TimingDiagramPanel/TimingDiagramButtons.vue
- src/components/Panels/TimingDiagramPanel/TimingDiagramPanel.vue
- src/locales/en.json
- src/locales/hi.json
- src/simulator/src/plotArea.js
Fixes Timing Diagram to Vue component
> feat(gsoc): convert timing diagram to vue component 

- src/components/Panels/PropertiesPanel/LayoutProperty/LayoutProperty.vue
- src/simulator/src/layoutMode.js
- src/simulator/src/listeners.js
- src/simulator/src/ux.js
Fixes  Layout mode loading error & layoutEditor panel
- fix layout mode crashing simualtor
- fix layout mode layout view of circuit not loading
- fix layout panel methods
- remove jQuery , jQuery ui & DOM manipulation 
N/A
> feat(gsoc): layout mode fix

- src/components/TabsBar/TabsBar.vue
- src/pages/embed.vue
- src/pages/simulatorHandler.vue
- src/router/index.ts
- src/simulator/src/Verilog2CV.js
- src/simulator/src/circuit.js
- src/simulator/src/data/save.js
- src/simulator/src/embed.js
- src/simulator/src/setup.js
Fixes add embed view of simulator, for circuit preview
[Screencast from 2023-09-06 19-41-51.webm](https://github.com/CircuitVerse/cv-frontend-vue/assets/96580571/3eb12c2e-4bad-4917-bd54-d41182f50f6e)
> feat(gsoc): embed view of simulator

- package-lock.json
- package.json
- src/components/MessageBox/messageBox.vue
- src/components/Navbar/Hamburger/Hamburger.vue
- src/components/ReportIssue/ReportIssueButton.vue
- src/styles/color_theme.scss
- src/styles/css/2-basics/base.scss
- src/styles/css/5-layout/simulator.scss
Fixes #196 
- Upgraded the font awesome from V5 to V6 to remove the console errors / warnings 
- Commented the hamburger.css file import causing warnings in the console 
- commented `import { defineProps, defineEmits } from 'vue' ` since its not required any more.  
- Removed JQuery from `color_theme.scss` 
- Removed js comments from CSS files 
- Removed warning from console while building the simulator  
> Removing console warnings and errors

- LICENSE
- src/styles/css/main.stylesheet.css
> fix: remove 'overflow' property in user-field class

- src/components/DialogBox/HexBinDec.vue
- src/simulator/src/utils.js
- src/simulator/src/ux.js
> Removing jQuery from and cleaning up HexBinDec.vue

- src/components/DialogBox/BooleanTable.vue
- src/components/DialogBox/CombinationalAnalysis.vue
Fixes #
The print tables in boolean tables couldn't generate the whole pdf, instead only a portion of it was visible. I fixed the small issue in UI part, so that the whole truth table could be generated in the PDF format (tldr; scroll issue fixed in print table).
resolve #198 
Here, only one page was visible. 
Here, all the pages and cells in the table are visible.
> feat: fixed printing bool tables

- README.md
- vite.config.ts
Fixes #258 
Added Documentation for Stackblitz Setup
> feat(docs): Added Documentation for Stackblitz Setup

- src/components/helpers/createNewProject/TextEditor.vue
Removed warnings and errors from the TextEditor.vue file
Changes Done:-
1. Adjusted the positions for the elements
2. Added the appearance: none in the CSS styles
3.  Added the key for the tags having v-for: 
Console before changes 
Console after changes
> Removing Warnings and Errors from TextEditor.vue file

- src/components/Panels/ElementsPanel/ElementsPanel.vue
Fixes #262
Previously, when searching for something on the search bar of ElementsPanel, it used to give elements that contained the search input as a substring in the name of the element.
I have added a new section that will show the categories that match the search input. To do the same, I have added another ```v-expansion-panel``` below the one that shows matched elements.
I haven't changed the code that is used to show all categories. I did it because I believe it will increase the readability of the code.
This feature will improve the accessibility of the search option. **It will be even more helpful if, at a later stage, more categories are added.**
The search algorithm finds categories, for which any word in the category name starts with the search input. (Comparision is done after …
> Added matching categories to the search results of ElementsPanel for better accessibility.

- src/simulator/src/tutorials.js
- src/styles/tutorials.scss
Fixes #283
- Updated the tour guide configuration (`tour` array) to replace the element selector to the correct element.
- Adjusted the CSS styling of `.bug-guide .right` class, ensuring that the popover tip points directly to the report system button.
- before the changes:
- after the changes:
> Fix: 'Report System' Element Not Highlighted in Tour Guide

- src/components/DialogBox/SaveImage.vue
Proof of Work GSoC'24
- removed all JQuery DOM manipulations with Vue's reactive System
- Added standard typescript type annotations
https://github.com/CircuitVerse/cv-frontend-vue/assets/91966855/46275587-9bde-4e6d-ad8b-82e87ea01bbf
> refactor: converted all DOM manipulations to Vue's reactive system in SaveImage.vue

- src/components/DialogBox/HexBinDec.vue
- src/styles/color_theme.scss
- src/styles/css/main.stylesheet.css
Proof of work GSoC'24
moved global css of HexBinDec to component scope
> refactor: moved global css of HexBinDec to component scope

- src/components/Panels/ElementsPanel/ElementsPanel.vue
Fixes #285 
Adjusted the styling of the panel body in the `ElementsPanel` component to enable vertical scrolling. This ensures that the panel remains fully accessible even when expanded elements exceed the viewport height.
- before the changes:
https://github.com/CircuitVerse/cv-frontend-vue/assets/89861718/837ec6ce-52d4-40a2-96ef-b1517cd80793
- after the changes:
https://github.com/CircuitVerse/cv-frontend-vue/assets/89861718/ea26021b-8192-46a3-86af-6754b8f0c331
> Fix: Circuit Elements Panel Bug Hiding Lower Section

- src/components/Panels/PropertiesPanel/PropertiesPanel.vue
- src/simulator/src/engine.js
Fixes #292 
Added a check `if` element that is selected is new then set the label to `""` empty string
https://github.com/CircuitVerse/cv-frontend-vue/assets/91966855/b9d05eb8-7bc6-41e2-ba54-d65da6e80f59
> fix: last selected element label duplication fixed

- README.md
Fixes #294
- Added new sections to provide users and contributors with clearer guidance and information:
- Project Overview
- Community Engagement
- Code of Conduct
- Contributing Guidelines
- License
> Enhanced README with Key Sections

- src/simulator/src/sequential/Clock.js
> fix(clock): add missing help button

- src/simulator/src/canvasApi.js
This pull request addresses issue #310 :  Corner Triangular Edge Display Issue Of Logic Gates.
The issue arises due to the upper edges of circuit elements, particularly gates with triangular corners like OR Gate, NOR Gate, X-OR Gate, etc., being slightly distorted on the default zoom level. This distortion affects the UI negatively, causing an inconsistent appearance.
Upon investigating, it was found that the distortion occurs during the drawing of the gates. While drawing curves, the `Math.round()` function is correctly used to round off decimal numbers. However, when moving the canvas context (ctx), `Math.round()` is not applied to the moving coordinates. As a result, when the `ctx.closePath()` method is called, the presence of decimal numbers, particularly .5 in both x and y …
> fix(UI): gates upper edge drawing issue

- src/components/TabsBar/TabsBar.vue
Fixes #277 
I have changed the z-index property of the component that is displaying over the options of the Navbar.
After the change:
> Fix: First option of navbar's dropdown was hidden

- src/simulator/src/contention.js
- src/simulator/src/engine.js
- src/simulator/src/modules/TriState.js
- src/simulator/src/node.js
PR ref - [#4882](https://github.com/CircuitVerse/CircuitVerse/pull/4882)
> feat(gsoc'24): Deferred Contentions (#4882)
