CircuitVerse/cv-frontend-vue

README.md
fix: Typo in line 9 of README.md
changes Sate to State
=> fix(typo): changes sate to state

src/simulator/src/tutorials.js
=> refactor: removed JQuery dependency in tutorials.js file

src/simulator/src/Verilog2CV.js
=> refactor: removed JQuery dependency in Verilog2CV.js file

src/simulator/src/ux.js
Fixes:- #27 
Describe the changes you have made in this PR -
I have removed jquery dependency in `ux.js` file
Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.
=> feat: remove jquery dependency in ux.js file

src/simulator/src/verilog.js
Fixes: #27 
Removed JQuery dependency from verilog.js file
=> refactor: removed JQuery dependency from verilog.js file

src/simulator/src/restrictedElementDiv.js
Fixes: #27 
Removed JQuery dependency from restrictedElementDiv.js file
=> refactor: removed JQuery dependency from restrictedElementDiv.js file

src/simulator/src/ux.js
Reverts CircuitVerse/cv-frontend-vue#33
=> Revert "feat: remove jquery dependency in ux.js file"

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Fixes: #42
- Additions:
1. Bug report template
2. feature request template
3. config to redirect to slack
4. pull request template
@devartstar @tachyons could you please review the PR and suggest if any changes are required, Thanks.
=> added: contributor's workflow

src/styles/css/main.stylesheet.css
changed circuits tabs inline flex style from inline block and aligned it  center & centered the add button according to it
=> style: :art: fixed padding and alignment issue in tabsbar - issue(#81) 

src/simulator/src/canvasApi.js
Fixes #84
1. made changes into the canvasApi.js , in dots function
2. added drawing of dots when dots is true
3. changed the variables from var to const and let 
4. did required changes for the panning effect to work
https://user-images.githubusercontent.com/96580571/222765338-df7488ce-c85c-457f-a71d-6ba7b5158221.mp4
=> fix(canvas): fix simulator backgroud grid panning effect, canvasApi.js fixed

src/components/DialogBox/HexBinDec.vue
=> fix: hexbindec convertor error

.github/workflows/eslint.yml
Reverts CircuitVerse/cv-frontend-vue#145
=> Revert "Simplify eslint action"

src/components/DialogBox/InsertSubcircuit.vue
Fixes Insert subcircuit logic 
- fix active circuit option to add as subcircuit
- fix `new circuit +` 
- fix available sub circuit logic
=> feat(gsoc): fix insert subcircuit logic & error

src/pages/simulatorHandler.vue, src/simulator/src/Verilog2CV.js, src/simulator/src/data/save.js, src/simulator/src/setup.js
Fixes # update the api endponts with the merged version of apis at [CircuitVerse/pr-3862](https://github.com/CircuitVerse/CircuitVerse/pull/3862)
- update the api endpoints
N/A
=> feat(gsoc): update api endpoints with the new api/v1 endpoints

README.md
=> Updated the Readme with setup information and pending tasks

src/simulator/src/drag.ts
Fixes #194 
-Changes in Drag.ts, changed the z-index.
Before changes: -
After changes: -
=> feat(drag): bug fixes for drag.ts

src/simulator/src/ux.js
Event listeners are continuously registered without being removed.
=> Fixing event leak

src/components/Panels/ElementsPanel/ElementsPanel.vue
Fixes #249 
added `mousedown` event for both searched and category elements
https://github.com/CircuitVerse/cv-frontend-vue/assets/91966855/52dbe3ed-a8b1-460c-95d4-52d2aa8320c5
=> feat: added dragability for the circuit elements in panel

src/components/ContextMenu/ContextMenu.vue, src/components/DialogBox/BooleanTable.vue, src/components/DialogBox/CombinationalAnalysis.vue, src/components/DialogBox/CustomShortcut.vue, src/components/DialogBox/ImportProject.vue, src/components/DialogBox/OpenOffline.vue, src/components/DialogBox/Themes/ApplyThemes.vue, src/components/Dropdown/DropDown.vue, src/components/Panels/PropertiesPanel/ModuleProperty/ProjectProperty/ProjectProperty.vue, src/components/Panels/TimingDiagramPanel/TimingDiagramPanel.vue, src/components/TabsBar/TabsBar.vue, src/pages/embed.vue, src/pages/simulatorHandler.vue, src/simulator/src/combinationalAnalysis.js, src/simulator/src/hotkey_binder/keyBinder.js, src/simulator/src/modules/Splitter.js, src/simulator/src/setup.js, src/simulator/src/subcircuit.js, src/simulator/src/testbench.js, src/simulator/src/themer/customThemer.js, src/simulator/src/themer/themer.js, src/simulator/src/ux.js, src/simulator/src/verilog.js
Fixes #279 
- unwanted console logs removed
- transition item-key missing warning removed
Note: The warning related to the transition group is a issue related to vue.draggable.next library which currently stays but if i find a way to fix it i will create a follow up PR
=> refactor: unwanted logs and warnings removed from console

src/simulator/src/tutorials.js
PR ref - [#4571](https://github.com/CircuitVerse/CircuitVerse/pull/4571)
=> feat(gsoc'24): test-bench added in tutorial guide #4571

src/styles/css/testCreator.css
PR ref - [#4594](https://github.com/CircuitVerse/CircuitVerse/pull/4594)
=> fix(gsoc'24): testbench buttons style updated (#4594)

src/simulator/src/node.js, src/simulator/src/sequential/TTY.js, src/simulator/src/ux.js
PR ref - [#3834](https://github.com/CircuitVerse/CircuitVerse/pull/3834)
=> fix(gsoc'24): Fix small typos in function comments (#3834)

src/simulator/src/sequential/SRflipFlop.js
ref PR - [#3189](https://github.com/CircuitVerse/CircuitVerse/pull/3189)
=> fix(gsoc'24): issue of connect only r input crash simulator (#3189)

src/simulator/src/modules/AndGate.js, src/simulator/src/modules/NotGate.js, src/simulator/src/modules/OrGate.ts, src/simulator/src/modules/TwoComplement.js, src/simulator/src/modules/XorGate.js
ref PR - [#4643](https://github.com/CircuitVerse/CircuitVerse/commit/6bf0d3b9494a20bf9ac72e0de36f716dcc920328)
=> fix(gsoc'24): capitalisation in simulator (#4643)

src/simulator/src/modules/DigitalLed.js, src/simulator/src/modules/PriorityEncoder.js, src/simulator/src/modules/RGBLed.js, src/simulator/src/modules/VariableLed.js
PR ref - [#4278](https://github.com/CircuitVerse/CircuitVerse/pull/4278)
=> fix(gsoc'24): corrected alignment of some element labels (#4278)

src/simulator/src/modules/ControlledInverter.js, src/simulator/src/node.js
PR ref - [#4887](https://github.com/CircuitVerse/CircuitVerse/pull/4887)
=> fix(gsoc'24): Fix ControlledInverter - similar to tristate (#4887)

src/simulator/src/engine.js
updates from main repo - https://github.com/CircuitVerse/CircuitVerse/commit/abed9baa77d5f057424f435b968ec52b7a759045
=> update(gsoc'24): Reset nodes on contention

src/simulator/src/node.js
updates from main repo - https://github.com/CircuitVerse/CircuitVerse/commit/c31612b3a0f9b5df93767acb4fe4ccdc3f197678
=> fix(gsoc'24): Remove output contentions even on undef propagation
